### ISSUE TITLE
Usable in a non-public production system?

### ISSUE THREAD

**Issue by qume** [UprootLabs/poly-flif#17]
This project is fantastic, but I see that the repo hasn't been updated in a while. 

Just curious to get a status update. I'm interested in using this for archival storage of a few TB of aerial images which need to be both stored lossless, but also queried for low-fi versions (for preview / index)

I can have everything backed up in original TIFF offline, so no risk there. Would love to choose this as our softwares new internal standard.

**Comment by jonsneyers** [comment]
The FLIF bitstream is in the process of being finalized (should be ready by the end of the month), and I think @hrj is waiting to update poly-flif until the bitstream is final.

**Comment by hrj** [comment]
@qume @jonsneyers I spent some time today morning to merge the changes from upstream. I am able to compile the merged code but there's some run-time error. Unfortunately, I don't have time to debug it now.

I have pushed the commits here; if anyone would like to debug and make a PR, they are welcome :)

@qume For production use, I suggest waiting until the bitstream format is finalised. cheers!

**Comment by hrj** [comment]
I have fixed the errors, and poly-flif code is in sync with upstream now.

As soon as a release is announced by @jonsneyers,  it should be possible to use FLIF and poly-flif in production.
