### ISSUE TITLE
Update poly-filf

### ISSUE THREAD

**Issue by skytz** [UprootLabs/poly-flif#18]
I saw there wore some additional classes created to build it with emscripten.

How do i update the repo to the latest version of flif?

Thank you

**Comment by hrj** [comment]
At the level of git, poly-FLIF is a branch. You can simply merge from FLIF master. Sometimes there are trivial merge conflicts that need to be resolved.

---

In the current poly-flif master, the code compiles but gives a run-time error. I have not found time to investigate it further.

**Comment by hrj** [comment]
The code has been updated to upstream master branch, and the bugs have been resolved.
I have updated the demo as well.

Let me know if something doesn't work.
