### ISSUE TITLE
Decode in web worker

### ISSUE THREAD

**Issue by FallingSnow** [UprootLabs/poly-flif#27]
Is it possible to decode a flif in a web worker? I'm using [canvas-webworker ](https://www.npmjs.com/package/canvas-webworker) with webpack in a web worker but keep running into this issue: `Cannot set property 'PolyFlif' of undefined`.

The referenced line is:
```javascript
  }var ic = !1;c.noInitialRun && (ic = !1);c.noExitRuntime = !0;jb();window.PolyFlif = c.PolyFlif.extend("PolyFlif", { __construct: function __construct(b) {
```
at window.PolyFlif.

I've tried adding `let window = self` before importing the script but it seems to have no effect.

**Comment by hrj** [comment]
I haven't tested / developed support for webworkers yet. It shouldn't be too complicated, but I don't think it will be very trivial either.

Might be sometime before I get to this. PRs welcome :smile:

**Comment by FallingSnow** [comment]
I actually did manage to get it to work by adding `var window = self` to the beginning of the PolyFlif.js file itself and removing the section referring to document. However it doesn't seem to manipulate the canvas correctly when used with `canvas-webworker`. All the imagedata is set to 0. Since this is the only library that allows me to use a canvas in webworkers I feel I've hit a dead end.

**Comment by FallingSnow** [comment]
I have finally got it done using https://github.com/SaschaNaz/libflif.js but it is

- significantly slower (500%) - I believe this has to do with libflif not scaling beforehand, if that makes sense. It gets closer to same speed the closer to original scale it gets.
- Very unstable on chromium-dev

**Comment by hrj** [comment]
I am trying to get back into development but, FWIW, I am stuck at getting the latest emscripten to compile on Linux :confounded: 

How I would approach this without modifying the library:
* mock the window object like you did
* mock the document object too (could probably just be an empty object)
* mock the canvas, but don't use any third party library. You can just mock the few functions that are called, such as getImageData(), putImageData(), getContext(), etc. These functions would need to shuttle the data to the actual canvas in the main thread. If I remember right, image data can be shared between main thread and worker thread. So you just need to proxy it across the worker message queue.
