### ISSUE TITLE
flif.js:147 Uncaught TypeError: Cannot convert "undefined" to int

### ISSUE THREAD

**Issue by ibrokemypie** [UprootLabs/poly-flif#44]
flif.js:147 Uncaught TypeError: Cannot convert "undefined" to int
    at Object.toWireType (flif.js:147)
    at PolyFlif$startCount [as startCount] (eval at Va (flif.js:13), <anonymous>:11:26)
    at self.onmessage (flif.js:177)
toWireType @ flif.js:147
PolyFlif$startCount @ VM46:11
self.onmessage @ flif.js:177
flif.js:147 Uncaught TypeError: Cannot convert "undefined" to int
    at Object.toWireType (flif.js:147)
    at PolyFlif$startCount [as startCount] (eval at Va (flif.js:13), <anonymous>:11:26)
    at self.onmessage (flif.js:177)
toWireType @ flif.js:147
PolyFlif$startCount @ VM46:11
self.onmessage @ flif.js:177

**Comment by ibrokemypie** [comment]
This is happening on my own test site as well as https://uprootlabs.github.io/poly-flif/polyflif-sample.html
Currently happening on Chrome Version 62.0.3178.0 (Official Build) dev (64-bit), Safari Version 10.1.2 (12603.3.8) and Firefox Nightly 
57.0a1, all on macOS sierra

**Comment by hrj** [comment]
Thanks for that hint! That made me realize that it's a silly problem.

Fixed and released as part of 0.8.2:
https://github.com/UprootLabs/poly-flif/releases/tag/v0.8.2
