### ISSUE TITLE
poly-flif vs libflif

### ISSUE THREAD

**Issue by arasouli91** [UprootLabs/poly-flif#49]
I am trying to understand how I can help with getting FLIF on the web.
But, I am not sure why there is two projects trying to do the same. What's the difference?
It looks like asm.js is being used here, and https://github.com/saschanaz/libflif.js uses WASM.

I've been tasked to make progress on this so I am trying to gauge which repo is further along so that I can focus my efforts there.

Another difference is here TOTAL_MEMORY is set at 100663296 , and in libflif ALLOW_MEMORY_GROWTH is turned on instead. This is just a performance trade off.

I've noticed some issues in libflif that seem to indicate partial functionality:
https://github.com/saschanaz/libflif.js/issues/6 https://github.com/saschanaz/libflif.js/issues/14
Are these not issues here as well?

**Comment by hrj** [comment]
@saschanaz has answered this question well on https://github.com/saschanaz/libflif.js/issues/19

I have summarized my understanding in [this wiki page](https://github.com/UprootLabs/poly-flif/wiki/Comparison-with-other-libraries).
