### ISSUE TITLE
Comparison with Adam7 PNG

### ISSUE THREAD

**Issue by FLIF-hub** [UprootLabs/poly-flif#5]
A side-by-side comparison of FLIF and Adam7 interlaced PNG would be nice. It would be interesting to compare those two interactively, both in absolute performance (same file size of truncated files) and relative performance (same percentage of truncation). For fairness, the PNG file should be progressively decoded with bilinear interpolation.

**Comment by hrj** [comment]
> both in absolute performance (same file size of truncated files) and relative performance (same percentage of truncation)

Implemented the absolute performance part.

The relative performance can be implemented. I am trying to plan the UI for this and other options. But I am not sure if `relative performance` has any practical significance.

**Comment by FLIF-hub** [comment]
Not really, except to compare the interlacing itself, in isolation. Though even for that it would be better to make a FLIF which uses the entropy encoding of PNG. So maybe just drop that relative performance comparison, it would be hard to draw any conclusions from it anyway.

**Comment by hrj** [comment]
Dropping relative perf comparison.
