### ISSUE TITLE
Animated FLIF frame delays are not respected

### ISSUE THREAD

**Issue by ghost** [UprootLabs/poly-flif#51]
I encoded a GIF file (attached) with gif2flif (from FLIF's repo). The resulting FLIF (attached as .flif.gz) had the correct frame delays of 80 milliseconds. I then loaded the animated FLIF in poly-flif with an HTML file:

```html
<script src="flif.js"></script>
<canvas data-polyflif-src="skunk.flif"></canvas>
```

The resulting page is the attached MP4 file (gzipped). The displayed image had delays which were much shorter than the input FLIF file.

Deconstructing the FLIF with `flif skunk.flif skunk.png` reported correct timings. Reconstructing the GIF with `convert -loop 0 -delay 8 skunk*.png skunk-reconstructed.gif` created a correctly timed image.

![skunk](https://user-images.githubusercontent.com/31974925/54447385-3b9b7180-4741-11e9-9e3f-059cbbbc2325.gif)

[skunk.flif.gz](https://github.com/UprootLabs/poly-flif/files/2972054/skunk.flif.gz)

[skunk.mp4.gz](https://github.com/UprootLabs/poly-flif/files/2972057/skunk.mp4.gz)

- poly-flif version: 0.8.2
- Browsers tested: Waterfox, Firefox, and Falkon (Chromium won't load the local files)
- OS: Xubuntu 18.04

**Comment by hrj** [comment]
@alexandercrypto Yeah, the support for animations is not complete. An issue exists for this already: #2, so let's use that.
